# Generated by Django 4.2.5 on 2024-03-16 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media/poster')),
                ('description', models.CharField(max_length=223)),
                ('is_first', models.BooleanField(default=False)),
                ('is_second', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.storage')),
            ],
        ),
    ]
